mklink /D DriveHUD.Common ..\DriveHUD\DriveHUD.Common
mklink /D PokerHandHistoryParser ..\DriveHUD\PokerHandHistoryParser
mklink /D DriveHUD.Common.Infrastructure ..\DriveHUD\DriveHUD.Common.Infrastructure
mklink /D DriveHUD.Common.Resources ..\DriveHUD\DriveHUD.Common.Resources
mklink /D DriveHUD.Common.Wpf ..\DriveHUD\DriveHUD.Common.Wpf
mklink /D DriveHUD.Controls ..\DriveHUD\DriveHUD.Controls
mklink /D DriveHUD.ViewModels ..\DriveHUD\DriveHUD.ViewModels
mklink /D Model ..\DriveHUD\Model
mklink /D DriveHUD.Entities ..\DriveHUD\DriveHUD.Entities
mklink /D DriveHUD.Common.Infrastructure ..\DriveHUD\DriveHUD.Common.Infrastructure
mklink /D .\tools\build\include ..\..\..\DriveHUD\tools\build\include
mklink /D .\tools\build\modules ..\..\..\DriveHUD\tools\build\modules